# ANALISIS HARGA KENDARAAN

## ANALISIS FAKTOR\-FAKTOR YANG MEMPENGARUHI HARGA KENDARAAN DENGAN SQL

# INFORMASI TABEL

In [1]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{"sortBy":[],"filters":[],"pageSize":10,"pageIndex":0,"columnOrder":["column_name","column_type","null","key","default","extra"],"hiddenColumnIds":[],"columnDisplayNames":[],"conditionalFilters":[],"cellFormattingRules":[],"wrappedTextColumnIds":[]}')
else:
  _deepnote_current_table_attrs = '{"sortBy":[],"filters":[],"pageSize":10,"pageIndex":0,"columnOrder":["column_name","column_type","null","key","default","extra"],"hiddenColumnIds":[],"columnDisplayNames":[],"conditionalFilters":[],"cellFormattingRules":[],"wrappedTextColumnIds":[]}'

df_3 = _dntk.execute_sql(
  'DESCRIBE \'Automotive Price Prediction-20260918-042121.csv\'',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_3

         column_name column_type null   key default extra
0               make     VARCHAR  YES  None    None  None
1              model     VARCHAR  YES  None    None  None
2               year      BIGINT  YES  None    None  None
3            mileage      BIGINT  YES  None    None  None
4          engine_hp      BIGINT  YES  None    None  None
5       transmission     VARCHAR  YES  None    None  None
6          fuel_type     VARCHAR  YES  None    None  None
7         drivetrain     VARCHAR  YES  None    None  None
8          body_type     VARCHAR  YES  None    None  None
9     exterior_color     VARCHAR  YES  None    None  None
10    interior_color     VARCHAR  YES  None    None  None
11       owner_count      BIGINT  YES  None    None  None
12  accident_history     VARCHAR  YES  None    None  None
13       seller_type     VARCHAR  YES  None    None  None
14         condition     VARCHAR  YES  None    None  None
15              trim     VARCHAR  YES  None    None  None
16       vehicle_age      BIGINT  YES  None    None  None
17  mileage_per_year      DOUBLE  YES  None    None  None
18  brand_popularity      DOUBLE  YES  None    None  None
19             price      DOUBLE  YES  None    None  None

#  PROFILING DATA

In [2]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_14 = _dntk.execute_sql(
  'SELECT \'make\' AS kolom, make AS nilai, COUNT(*) AS jumlah\nFROM \'Automotive Price Prediction-20260918-042121.csv\'\nGROUP BY make\n\nUNION ALL\n\nSELECT \'model\' AS kolom, model AS nilai, COUNT(*) AS jumlah\nFROM \'Automotive Price Prediction-20260918-042121.csv\'\nGROUP BY model\n\nUNION ALL\n\nSELECT \'transmission\' AS kolom, transmission AS nilai, COUNT(*) AS jumlah\nFROM \'Automotive Price Prediction-20260918-042121.csv\'\nGROUP BY transmission\n\nUNION ALL\n\nSELECT \'fuel_type\' AS kolom, fuel_type AS nilai, COUNT(*) AS jumlah\nFROM \'Automotive Price Prediction-20260918-042121.csv\'\nGROUP BY fuel_type\n\nUNION ALL\n\nSELECT \'drivetrain\' AS kolom, drivetrain AS nilai, COUNT(*) AS jumlah\nFROM \'Automotive Price Prediction-20260918-042121.csv\'\nGROUP BY drivetrain\n\nUNION ALL\n\nSELECT \'body_type\' AS kolom, body_type AS nilai, COUNT(*) AS jumlah\nFROM \'Automotive Price Prediction-20260918-042121.csv\'\nGROUP BY body_type\n\nUNION ALL\n\nSELECT \'exterior_color\' AS kolom, exterior_color AS nilai, COUNT(*) AS jumlah\nFROM \'Automotive Price Prediction-20260918-042121.csv\'\nGROUP BY exterior_color\n\nUNION ALL\n\nSELECT \'interior_color\' AS kolom, interior_color AS nilai, COUNT(*) AS jumlah\nFROM \'Automotive Price Prediction-20260918-042121.csv\'\nGROUP BY interior_color\n\nUNION ALL\n\nSELECT \'accident_history\' AS kolom, accident_history AS nilai, COUNT(*) AS jumlah\nFROM \'Automotive Price Prediction-20260918-042121.csv\'\nGROUP BY accident_history\n\nUNION ALL\n\nSELECT \'seller_type\' AS kolom, seller_type AS nilai, COUNT(*) AS jumlah\nFROM \'Automotive Price Prediction-20260918-042121.csv\'\nGROUP BY seller_type\n\nUNION ALL\n\nSELECT \'condition\' AS kolom, "condition" AS nilai, COUNT(*) AS jumlah\nFROM \'Automotive Price Prediction-20260918-042121.csv\'\nGROUP BY "condition"\n\nUNION ALL\n\nSELECT \'trim\' AS kolom, "trim" AS nilai, COUNT(*) AS jumlah\nFROM \'Automotive Price Prediction-20260918-042121.csv\'\nGROUP BY "trim"\n\nORDER BY jumlah DESC;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_14

                kolom      nilai  jumlah
0    accident_history       None  750133
1         seller_type     Dealer  699710
2        transmission  Automatic  500263
3        transmission     Manual  499737
4           condition       Good  499683
..                ...        ...     ...
164             model       RAV4    7880
165             model     Escape    7879
166             model   3 Series    7871
167             model    Corolla    7837
168             model         X5    7823

[169 rows x 3 columns]

### Nilai none dipertahankan karena belum dapat dipastikan apakah menunjukkan kendaraan tidak pernah mengalami kecelakaan atau merupakan data yang tidak diinput\. Penghapusan nilai tersebut berisiko menghilangkan informasi dari dataset karena memiliki jumlah data yang banyak\.

# CEK DUPLIKAT

In [3]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_5 = _dntk.execute_sql(
  'SELECT\n    make,\n    model,\n    year,\n    mileage,\n    engine_hp,\n    transmission,\n    fuel_type,\n    drivetrain,\n    body_type,\n    exterior_color,\n    interior_color,\n    owner_count,\n    accident_history,\n    seller_type,\n    condition,\n    trim,\n    vehicle_age,\n    mileage_per_year,\n    brand_popularity,\n    price,\n    COUNT(*) AS duplicate_count\nFROM \'Data Kotor Automotive Price Prediction.csv\'\nGROUP BY\n    make,\n    model,\n    year,\n    mileage,\n    engine_hp,\n    transmission,\n    fuel_type,\n    drivetrain,\n    body_type,\n    exterior_color,\n    interior_color,\n    owner_count,\n    accident_history,\n    seller_type,\n    condition,\n    trim,\n    vehicle_age,\n    mileage_per_year,\n    brand_popularity,\n    price\nHAVING COUNT(*) > 1;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_5

Empty DataFrame
Columns: [make, model, year, mileage, engine_hp, transmission, fuel_type, drivetrain, body_type, exterior_color, interior_color, owner_count, accident_history, seller_type, condition, trim, vehicle_age, mileage_per_year, brand_popularity, price, duplicate_count]
Index: []

[0 rows x 21 columns]

# CEK ANOMALI DATA NUMERIK

In [4]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_6 = _dntk.execute_sql(
  'SELECT * FROM \'Automotive Price Prediction-20260918-042121.csv\'\nWHERE \n  price <= 0 \n  OR year > 2026 OR year < 1900\n  OR mileage < 0 \n  OR engine_hp <= 0\n  OR vehicle_age < 0\n  OR mileage_per_year < 0\n  OR brand_popularity < 0\n  OR owner_count < 0;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_6

Empty DataFrame
Columns: [make, model, year, mileage, engine_hp, transmission, fuel_type, drivetrain, body_type, exterior_color, interior_color, owner_count, accident_history, seller_type, condition, trim, vehicle_age, mileage_per_year, brand_popularity, price]
Index: []

# VALIDASI DATA TANGGAL

In [5]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_10 = _dntk.execute_sql(
  'SELECT\n    COUNT(*) AS jumlah_tidak_konsisten\nFROM \'Automotive Price Prediction-20260918-042121.csv\'\nWHERE vehicle_age <> 2026 - year;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_10

   jumlah_tidak_konsisten
0                  960197

In [6]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_11 = _dntk.execute_sql(
  'SELECT\n    year,\n    vehicle_age,\n    2026 - year AS seharusnya\nFROM \'Automotive Price Prediction-20260918-042121.csv\'\nWHERE vehicle_age <> 2026 - year\nLIMIT 100;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_11

    year  vehicle_age  seharusnya
0   2016            9          10
1   2010           15          16
2   2016            9          10
3   2016            9          10
4   2018            7           8
..   ...          ...         ...
95  2015           10          11
96  2018            7           8
97  2018            7           8
98  2016            9          10
99  2017            8           9

[100 rows x 3 columns]

### Dilakukan pengecekan kolom vehicle\_age dengan rumus 2026 \- year\. Ditemukan selisih 1 tahun yang konsisten, kemungkinan dataset Kaggle dibuat pada tahun 2025 sedangkan analisis dilakukan di tahun 2026\. Maka dilakukan perhitungan ulang umur kendaraan agar sesuai dengan tahun analisis saat ini\.

# DATA OUTLIER

In [7]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_19 = _dntk.execute_sql(
  'SELECT\n    \'year\' AS kolom,\n    MIN(year) AS minimum,\n    MAX(year) AS maksimum,\n    AVG(year) AS rata_rata\nFROM \'Automotive Price Prediction-20260918-042121.csv\'\n\nUNION ALL\n\nSELECT\n    \'mileage\' AS kolom,\n    MIN(mileage) AS minimum,\n    MAX(mileage) AS maksimum,\n    AVG(mileage) AS rata_rata\nFROM \'Automotive Price Prediction-20260918-042121.csv\'\n\nUNION ALL\n\nSELECT\n    \'engine_hp\' AS kolom,\n    MIN(engine_hp) AS minimum,\n    MAX(engine_hp) AS maksimum,\n    AVG(engine_hp) AS rata_rata\nFROM \'Automotive Price Prediction-20260918-042121.csv\'\n\nUNION ALL\n\nSELECT\n    \'owner_count\' AS kolom,\n    MIN(owner_count) AS minimum,\n    MAX(owner_count) AS maksimum,\n    AVG(owner_count) AS rata_rata\nFROM \'Automotive Price Prediction-20260918-042121.csv\'\n\nUNION ALL\n\nSELECT\n    \'vehicle_age\' AS kolom,\n    MIN(vehicle_age) AS minimum,\n    MAX(vehicle_age) AS maksimum,\n    AVG(vehicle_age) AS rata_rata\nFROM \'Automotive Price Prediction-20260918-042121.csv\'\n\nUNION ALL\n\nSELECT\n    \'mileage_per_year\' AS kolom,\n    MIN(mileage_per_year) AS minimum,\n    MAX(mileage_per_year) AS maksimum,\n    AVG(mileage_per_year) AS rata_rata\nFROM \'Automotive Price Prediction-20260918-042121.csv\'\n\nUNION ALL\n\nSELECT\n    \'brand_popularity\' AS kolom,\n    MIN(brand_popularity) AS minimum,\n    MAX(brand_popularity) AS maksimum,\n    AVG(brand_popularity) AS rata_rata\nFROM \'Automotive Price Prediction-20260918-042121.csv\'\n\nUNION ALL\n\nSELECT\n    \'price\' AS kolom,\n    MIN(price) AS minimum,\n    MAX(price) AS maksimum,\n    AVG(price) AS rata_rata\nFROM \'Automotive Price Prediction-20260918-042121.csv\';',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_19

              kolom      minimum       maksimum      rata_rata
0              year  2000.000000    2025.000000    2017.453816
1           mileage   500.000000  300000.000000  112660.126464
2         engine_hp    90.000000     581.000000     235.664301
3       owner_count     1.000000       5.000000       3.477846
4       vehicle_age     1.000000      25.000000       7.585987
5  mileage_per_year    33.333333   55391.000000   14540.674200
6  brand_popularity     0.039318       0.040484       0.040001
7             price  1500.000000   93422.090000   20329.302593

# MENGATASI DATA OUTLIER MENGGUNAKAN METODE IQR

In [8]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_20 = _dntk.execute_sql(
  'WITH quartiles AS (\n    SELECT\n        \'year\' AS kolom,\n        year::DOUBLE AS nilai,\n        NTILE(4) OVER (ORDER BY year) AS kuartil\n    FROM \'Automotive Price Prediction-20260918-042121.csv\'\n\n    UNION ALL\n\n    SELECT\n        \'mileage\' AS kolom,\n        mileage::DOUBLE AS nilai,\n        NTILE(4) OVER (ORDER BY mileage) AS kuartil\n    FROM \'Automotive Price Prediction-20260918-042121.csv\'\n\n    UNION ALL\n\n    SELECT\n        \'engine_hp\' AS kolom,\n        engine_hp::DOUBLE AS nilai,\n        NTILE(4) OVER (ORDER BY engine_hp) AS kuartil\n    FROM \'Automotive Price Prediction-20260918-042121.csv\'\n\n    UNION ALL\n\n    SELECT\n        \'owner_count\' AS kolom,\n        owner_count::DOUBLE AS nilai,\n        NTILE(4) OVER (ORDER BY owner_count) AS kuartil\n    FROM \'Automotive Price Prediction-20260918-042121.csv\'\n\n    UNION ALL\n\n    SELECT\n        \'vehicle_age\' AS kolom,\n        vehicle_age::DOUBLE AS nilai,\n        NTILE(4) OVER (ORDER BY vehicle_age) AS kuartil\n    FROM \'Automotive Price Prediction-20260918-042121.csv\'\n\n    UNION ALL\n\n    SELECT\n        \'mileage_per_year\' AS kolom,\n        mileage_per_year AS nilai,\n        NTILE(4) OVER (ORDER BY mileage_per_year) AS kuartil\n    FROM \'Automotive Price Prediction-20260918-042121.csv\'\n\n    UNION ALL\n\n    SELECT\n        \'brand_popularity\' AS kolom,\n        brand_popularity AS nilai,\n        NTILE(4) OVER (ORDER BY brand_popularity) AS kuartil\n    FROM \'Automotive Price Prediction-20260918-042121.csv\'\n\n    UNION ALL\n\n    SELECT\n        \'price\' AS kolom,\n        price AS nilai,\n        NTILE(4) OVER (ORDER BY price) AS kuartil\n    FROM \'Automotive Price Prediction-20260918-042121.csv\'\n),\n\nstats AS (\n    SELECT\n        kolom,\n        MAX(CASE WHEN kuartil = 1 THEN nilai END) AS q1,\n        MIN(CASE WHEN kuartil = 4 THEN nilai END) AS q3\n    FROM quartiles\n    GROUP BY kolom\n)\n\nSELECT\n    s.kolom,\n    s.q1,\n    s.q3,\n    s.q3 - s.q1 AS iqr,\n    s.q1 - 1.5 * (s.q3 - s.q1) AS batas_bawah,\n    s.q3 + 1.5 * (s.q3 - s.q1) AS batas_atas,\n    SUM(\n        CASE\n            WHEN q.nilai < s.q1 - 1.5 * (s.q3 - s.q1)\n              OR q.nilai > s.q3 + 1.5 * (s.q3 - s.q1)\n            THEN 1\n            ELSE 0\n        END\n    ) AS jumlah_outlier\nFROM stats AS s\nJOIN quartiles AS q\n    ON s.kolom = q.kolom\nGROUP BY\n    s.kolom,\n    s.q1,\n    s.q3\nORDER BY s.kolom;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_20

,kolom,q1,q3,iqr,batas_bawah,batas_atas,jumlah_outlier
0,brand_popularity,0.039842,0.040148,0.000306,0.039383,0.040607,39318.0
1,engine_hp,162.000000,300.000000,138.000000,-45.000000,507.000000,1381.0
2,mileage,57654.000000,157865.000000,100211.000000,-92662.500000,308181.500000,0.0
3,mileage_per_year,10487.625000,18686.000000,8198.375000,-1809.937500,30983.562500,4163.0
4,owner_count,2.000000,5.000000,3.000000,-2.500000,9.500000,0.0
5,price,10324.520000,27601.410000,17276.890000,-15590.815000,53516.745000,25524.0
6,vehicle_age,5.000000,10.000000,5.000000,-2.500000,17.500000,6029.0
7,year,2015.000000,2020.000000,5.000000,2007.500000,2027.500000,6029.0

### Berdasarkan metode IQR, ditemukan outlier pada beberapa variabel numerik seperti brand popularity, engine hp, mileage per year, price, vehicle age, dan year\. Outlier tidak langsung dihapus karena nilai tersebut belum tentu merupakan kesalahan data dan masih dapat merepresentasikan kondisi kendaraan yang sebenarnya\.

# STATISTIK

In [9]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_9 = _dntk.execute_sql(
  'SELECT \n  COUNT (*) total_vehicles,\n  MIN(price) as harga_terendah,\n  MAX(price) as harga_termahal,\n  MEDIAN(price) as median_harga,\n  AVG(price) as rata_harga,\n  AVG(mileage) as rata_mileage,\n  AVG(vehicle_age) as rata_umur_mobil,\n  AVG(engine_hp) as rata_tenaga_mesin,\nFROM \'Data Kotor Automotive Price Prediction.csv\';',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_9

,total_vehicles,harga_terendah,harga_termahal,median_harga,rata_harga,rata_mileage,rata_umur_mobil,rata_tenaga_mesin
0,1000000,1500.0,93422.09,17864.74,20329.302593,112660.126464,7.585987,235.664301

### Dari total 1\.000\.000 data kendaraan, dapat diketahui bahwa harga kendaraan memiliki nilai minimum sebesar $1\.500 dan nilai maksimum sebesar $93\.422,09\. Nilai median harga kendaraan adalah $17\.863,74, sedangkan rata\-rata harga kendaraan sebesar $20\.329,30\.

### Selain harga, statistik awal menunjukkan bahwa rata\-rata mileage kendaraan adalah sekitar 112\.660, rata\-rata usia kendaraan sebesar 7,59 tahun, dan rata\-rata tenaga mesin sebesar 235,66 HP\.

### Rata\-rata harga lebih tinggi dari median\. Ini menunjukkan bahwa sebagian kecil kendaraan memiliki harga yang cukup tinggi, sehingga membuat rata\-rata harga menjadi lebih tinggi\.

### Untuk data harga 1500, ditetapkan minimal harga / harga terendah kemungkinan bertujuan untuk menghindari nilai 0 atau outlier yang mengganggu perhitungan rata\-rata\.

# ANALISIS HARGA BERDASARKAN MODEL KENDARAAN

In [10]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{"sortBy":[],"filters":[],"pageSize":10,"pageIndex":0,"columnOrder":["make","model","total_vehicles","average_price","median_price"],"hiddenColumnIds":[],"columnDisplayNames":[],"conditionalFilters":[],"cellFormattingRules":[],"wrappedTextColumnIds":[]}')
else:
  _deepnote_current_table_attrs = '{"sortBy":[],"filters":[],"pageSize":10,"pageIndex":0,"columnOrder":["make","model","total_vehicles","average_price","median_price"],"hiddenColumnIds":[],"columnDisplayNames":[],"conditionalFilters":[],"cellFormattingRules":[],"wrappedTextColumnIds":[]}'

df_12 = _dntk.execute_sql(
  'SELECT\nmake,\nmodel,\nCOUNT() AS total_vehicles,\nROUND(AVG(price), 2) AS average_price,\nPERCENTILE_CONT(0.5)\nWITHIN GROUP (ORDER BY price) AS median_price\nFROM \'Automotive Price Prediction-20260918-042121.csv\'\nGROUP BY make, model\nHAVING COUNT() >= 10\nORDER BY average_price DESC;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_12

           make        model  total_vehicles  average_price  median_price
0       Porsche        Macan           10034       43241.53     41804.020
1       Porsche     Panamera           10090       42989.57     41368.450
2       Porsche      Cayenne           10070       42939.76     41261.020
3       Porsche          911           10016       42847.65     40986.685
4    Land Rover  Range Rover           13389       39607.14     38045.580
..          ...          ...             ...            ...           ...
100         Kia      Sorento            8097       10172.99      9544.870
101     Hyundai      Elantra            9707        9961.34      9238.460
102     Hyundai       Tucson            9860        9930.03      9226.855
103     Hyundai     Santa Fe            9874        9826.82      9176.490
104     Hyundai       Sonata            9877        9776.31      9095.400

[105 rows x 5 columns]

### Berdasarkan data pada tabel diatas dapat disimpulkan bahwa terdapat perbedaan harga yang cukup besar antar\-model kendaraan\. Model seperti Macan, Cayenne dan 911 memiliki rata\-rata harga yang lebih tinggi dibandingkan banyak model lainnya\. Kendaraan dengan rata\-rata harga paling ekonomis/terendah didominasi oleh Merek Hyundai dengan model Sonata, Santa Fe dan Tucson\.

### Rekomendasi:
Model kendaraan dapat digunakan sebagai dasar segmentasi harga dan inventory\. Kendaraan dengan model yang memiliki rata\-rata harga tinggi dapat ditempatkan pada segmen premium/mewah dan model kendaraan dengan harga terendah dapat ditempatkan pada segmen Ekonomis dengan strategi harga yang berbeda\.

# ANALISIS HARGA BERDASARKAN KONDISI KENDARAAN & RIWAYAT KECELAKAAN

In [20]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_15 = _dntk.execute_sql(
  'SELECT\ncondition,\nCOUNT(*) AS total_vehicles,\nROUND(AVG(price), 2) AS average_price,\nPERCENTILE_CONT(0.5)\nWITHIN GROUP (ORDER BY price) AS median_price\nFROM \'Automotive Price Prediction-20260918-042121.csv\'\nGROUP BY condition,\nORDER BY average_price DESC;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_15

   condition  total_vehicles  average_price  median_price
0  Excellent          400373       21136.66      18593.63
1       Good          499683       20125.60      17718.60
2       Fair           99944       18113.48      15963.25

In [22]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_21 = _dntk.execute_sql(
  'SELECT\naccident_history,\nCOUNT(*) AS total_vehicles,\nROUND(AVG(price), 2) AS average_price,\nPERCENTILE_CONT(0.5)\nWITHIN GROUP (ORDER BY price) AS median_price\nFROM \'Automotive Price Prediction-20260918-042121.csv\'\nGROUP BY accident_history\nORDER BY average_price DESC;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_21

  accident_history  total_vehicles  average_price  median_price
0             None          750133       21001.71      18525.25
1            Minor          199981       18936.21      16670.75
2            Major           49886       15802.86      13890.95

### Berdasarkan data pada tabel harga berdasarkan kondisi harga dapat disimpulkan kendaraan dengan kondisi Excellent memiliki rata\-rata harga tertinggi, sedangkan kendaraan dengan kondisi Fair memiliki rata\-rata harga terendah\. Berdasarkan tabel harga berdasarkan riwayat kecelakaan, di antara kendaraan yang memiliki informasi riwayat kecelakaan, kendaraan dengan riwayat kecelakaan Major memiliki rata\-rata harga lebih rendah dibandingkan kendaraan dengan riwayat Minor\.

### Rekomendasi :
Kondisi kendaraan dan riwayat kecelakaan perlu diperhatikan dalam proses penentuan harga\. Selain itu, informasi accident history sebaiknya dilengkapi karena sebagian besar data belum memiliki informasi tersebut\.

# ANALISIS HARGA BERDASARKAN TAHUN KENDARAAN

In [24]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_18 = _dntk.execute_sql(
  'SELECT\nCASE\nWHEN vehicle_age <= 3 THEN \'0-3 years\'\nWHEN vehicle_age <= 7 THEN \'4-7 years\'\nWHEN vehicle_age <= 10 THEN \'8-10 years\'\nELSE \'>10 years\'\nEND AS age_group,\nCOUNT(*) AS total_vehicles,\nROUND(AVG(price), 2) AS average_price\nFROM \'Automotive Price Prediction-20260918-042121.csv\'\nGROUP BY age_group\nORDER BY average_price DESC;\n\n',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_18

    age_group  total_vehicles  average_price
0   0-3 years          158247       35834.66
1   4-7 years          341765       24182.80
2  8-10 years          273289       15994.91
3   >10 years          226699        8921.55

### Berdasarkan data pada tabel diatas dapat disimpulkan bahwa harga kendaraan cenderung lebih rendah ketika usia kendaraan semakin tinggi\. Kendaraan berusia 1–5 tahun memiliki rata\-rata harga yang jauh lebih tinggi dibandingkan kendaraan berusia 10–25 tahun\.

### Rekomendasi:
Dalam menentukan harga kendaraan, usia kendaraan perlu menjadi salah satu faktor utama karena kendaraan yang lebih tua cenderung memiliki nilai jual lebih rendah\.

# ANALISIS HARGA BERDASARKAN ENGINE HP

In [28]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_17 = _dntk.execute_sql(
  'SELECT\nCASE\nWHEN engine_hp < 150 THEN \'<150 HP\'\nWHEN engine_hp < 250 THEN \'150-249 HP\'\nWHEN engine_hp < 350 THEN \'250-349 HP\'\nELSE \'350+ HP\'\nEND AS hp_group,\nCOUNT(*) AS total_vehicles,\nROUND(AVG(price), 2) AS average_price\nFROM \'Automotive Price Prediction-20260918-042121.csv\'\nGROUP BY hp_group\nORDER BY average_price DESC;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_17

     hp_group  total_vehicles  average_price
0     350+ HP          125351       37693.97
1  250-349 HP          263176       26422.26
2  150-249 HP          424984       15509.48
3     <150 HP          186489       11042.70

### Dari analisis pada tabel diatas, kendaraan dengan tenaga mesin lebih tinggi cenderung memiliki harga yang lebih tinggi\. Kelompok kendaraan dengan 300–581 HP memiliki rata\-rata harga hampir tiga kali kelompok 90–162 HP\.

### Rekomendasi:
Tenaga mesin dapat dipertimbangkan dalam segmentasi harga kendaraan, terutama untuk kendaraan dengan spesifikasi mesin tinggi

# ANALISIS HARGA BERDASARKAN MILEAGE

In [26]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_16 = _dntk.execute_sql(
  'SELECT\nCASE\nWHEN mileage < 30000 THEN \'<30K\'\nWHEN mileage < 60000 THEN \'30K-59K\'\nWHEN mileage < 100000 THEN \'60K-99K\'\nELSE \'100K+\'\nEND AS mileage_group,\nCOUNT(*) AS total_vehicles,\nROUND(AVG(price), 2) AS average_price\nFROM \'Automotive Price Prediction-20260918-042121.csv\'\nGROUP BY mileage_group\nORDER BY\nCASE mileage_group\nWHEN \'<30K\' THEN 1\nWHEN \'30K-59K\' THEN 2\nWHEN \'60K-99K\' THEN 3\nELSE 4\nEND;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_16

  mileage_group  total_vehicles  average_price
0          <30K          123761       35394.95
1       30K-59K          138273       28226.81
2       60K-99K          219950       22946.51
3         100K+          518016       13510.58

### Dari analisis pada tabel diatas, kendaraan dengan mileage yang lebih tinggi cenderung memiliki harga yang lebih rendah\. Kendaraan dengan mileage terendah memiliki rata\-rata harga lebih dari tiga kali kendaraan dengan mileage tertinggi\.

### Rekomendasi : 
Mileage dapat digunakan sebagai salah satu dasar dalam menentukan harga jual kendaraan\. Kendaraan dengan mileage tinggi perlu diberi penyesuaian harga yang sesuai\.

# ANALISIS MEREK DAN KONDISI

In [30]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{"sortBy":[],"filters":[],"pageSize":10,"pageIndex":0,"columnOrder":["make","condition","total_vehicles","average_price"],"hiddenColumnIds":[],"columnDisplayNames":[],"conditionalFilters":[],"cellFormattingRules":[],"wrappedTextColumnIds":[]}')
else:
  _deepnote_current_table_attrs = '{"sortBy":[],"filters":[],"pageSize":10,"pageIndex":0,"columnOrder":["make","condition","total_vehicles","average_price"],"hiddenColumnIds":[],"columnDisplayNames":[],"conditionalFilters":[],"cellFormattingRules":[],"wrappedTextColumnIds":[]}'

df_22 = _dntk.execute_sql(
  'SELECT\nmake,\ncondition,\nCOUNT() AS total_vehicles,\nROUND(AVG(price), 2) AS average_price\nFROM \'Automotive Price Prediction-20260918-042121.csv\'\nGROUP BY make, condition\nHAVING COUNT() >= 5\nORDER BY make, average_price DESC;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_22

          make  condition  total_vehicles  average_price
0        Acura  Excellent           15965       22822.81
1        Acura       Good           20182       21696.98
2        Acura       Fair            4000       19490.91
3         Audi  Excellent           16227       28801.00
4         Audi       Good           19846       27319.84
..         ...        ...             ...            ...
70  Volkswagen       Good           20089       12362.54
71  Volkswagen       Fair            3987       11210.47
72       Volvo  Excellent           15982       28102.62
73       Volvo       Good           19852       26669.95
74       Volvo       Fair            4008       23875.16

[75 rows x 4 columns]

### Berdasarkan data pada tabel diatas dapat dianalisis, pada berbagai tingkat kondisi kendaraan, terdapat perbedaan rata\-rata harga antar\-merek\. Acura memiliki rata\-rata harga tertinggi pada kondisi Excellent, Good, maupun Fair dalam dataset\.

### Rekomendasi:
Penentuan harga sebaiknya mempertimbangkan kombinasi antara merek dan kondisi kendaraan, bukan hanya menggunakan satu faktor\. Pendekatan ini dapat membantu membuat segmentasi harga yang lebih spesifik\.

## KESIMPULAN:
Analisis menunjukkan bahwa harga kendaraan memiliki hubungan dengan beberapa karakteristik kendaraan, terutama usia, mileage, tenaga mesin, kondisi, riwayat kecelakaan, serta model dan merek kendaraan\. Kendaraan yang lebih muda, memiliki mileage lebih rendah, tenaga mesin lebih tinggi, dan kondisi lebih baik cenderung memiliki harga yang lebih tinggi dalam dataset\. Oleh karena itu, faktor\-faktor tersebut dapat dipertimbangkan dalam proses segmentasi dan penentuan harga kendaraan\.

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=e94e5198-3a5e-4d12-b960-a95c93b4d83b' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' />
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>