# AUDIT 1 JUTA DATA MOBIL BEKAS VER SQL

## Yang dianalisa:
\- Bersihin data dari 1 juta jadi 989 ribu \(buang duplikat 4\.8%\)
\- Cek harga: paling murah 1500, paling banyak numpuk di bawah 5000
\- Bagi analisa jadi 4 bagian: harga, spek mesin, merek mobil dan tahun mobil\.

Tools: Deepnote SQL

# INFO TABEL

In [1]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{"sortBy":[],"filters":[],"pageSize":10,"pageIndex":0,"columnOrder":["column_name","column_type","null","key","default","extra"],"hiddenColumnIds":[],"columnDisplayNames":[],"conditionalFilters":[],"cellFormattingRules":[],"wrappedTextColumnIds":[]}')
else:
  _deepnote_current_table_attrs = '{"sortBy":[],"filters":[],"pageSize":10,"pageIndex":0,"columnOrder":["column_name","column_type","null","key","default","extra"],"hiddenColumnIds":[],"columnDisplayNames":[],"conditionalFilters":[],"cellFormattingRules":[],"wrappedTextColumnIds":[]}'

df_3 = _dntk.execute_sql(
  'DESCRIBE \'Automotive Price Prediction-20260918-042121.csv\'',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_3

         column_name column_type null   key default extra
0               make     VARCHAR  YES  None    None  None
1              model     VARCHAR  YES  None    None  None
2               year      BIGINT  YES  None    None  None
3            mileage      BIGINT  YES  None    None  None
4          engine_hp      BIGINT  YES  None    None  None
5       transmission     VARCHAR  YES  None    None  None
6          fuel_type     VARCHAR  YES  None    None  None
7         drivetrain     VARCHAR  YES  None    None  None
8          body_type     VARCHAR  YES  None    None  None
9     exterior_color     VARCHAR  YES  None    None  None
10    interior_color     VARCHAR  YES  None    None  None
11       owner_count      BIGINT  YES  None    None  None
12  accident_history     VARCHAR  YES  None    None  None
13       seller_type     VARCHAR  YES  None    None  None
14         condition     VARCHAR  YES  None    None  None
15              trim     VARCHAR  YES  None    None  None
16       vehicle_age      BIGINT  YES  None    None  None
17  mileage_per_year      DOUBLE  YES  None    None  None
18  brand_popularity      DOUBLE  YES  None    None  None
19             price      DOUBLE  YES  None    None  None

# CEK JUMLAH NULL

In [2]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_4 = _dntk.execute_sql(
  'SELECT\n  SUM(CASE WHEN make IS NULL OR make = \'\' THEN 1 ELSE 0 END) AS null_make,\n  SUM(CASE WHEN model IS NULL OR model = \'\' THEN 1 ELSE 0 END) AS null_model,\n  SUM(CASE WHEN year IS NULL THEN 1 ELSE 0 END) AS null_year,\n  SUM(CASE WHEN mileage IS NULL THEN 1 ELSE 0 END) AS null_mileage,\n  SUM(CASE WHEN engine_hp IS NULL THEN 1 ELSE 0 END) AS null_engine_hp,\n  SUM(CASE WHEN transmission IS NULL OR transmission = \'\' THEN 1 ELSE 0 END) AS null_transmission,\n  SUM(CASE WHEN fuel_type IS NULL OR fuel_type = \'\' THEN 1 ELSE 0 END) AS null_fuel_type,\n  SUM(CASE WHEN drivetrain IS NULL OR drivetrain = \'\' THEN 1 ELSE 0 END) AS null_drivetrain,\n  SUM(CASE WHEN body_type IS NULL OR body_type = \'\' THEN 1 ELSE 0 END) AS null_body_type,\n  SUM(CASE WHEN exterior_color IS NULL OR exterior_color = \'\' THEN 1 ELSE 0 END) AS null_exterior_color,\n  SUM(CASE WHEN interior_color IS NULL OR interior_color = \'\' THEN 1 ELSE 0 END) AS null_interior_color,\n  SUM(CASE WHEN owner_count IS NULL THEN 1 ELSE 0 END) AS null_owner_count,\n  SUM(CASE WHEN accident_history IS NULL OR accident_history = \'\' THEN 1 ELSE 0 END) AS null_accident,\n  SUM(CASE WHEN seller_type IS NULL OR seller_type = \'\' THEN 1 ELSE 0 END) AS null_seller_type,\n  SUM(CASE WHEN condition IS NULL OR condition = \'\' THEN 1 ELSE 0 END) AS null_condition,\n  SUM(CASE WHEN trim IS NULL OR trim = \'\' THEN 1 ELSE 0 END) AS null_trim,\n  SUM(CASE WHEN vehicle_age IS NULL THEN 1 ELSE 0 END) AS null_vehicle_age,\n  SUM(CASE WHEN mileage_per_year IS NULL THEN 1 ELSE 0 END) AS null_mileage_per_year,\n  SUM(CASE WHEN brand_popularity IS NULL THEN 1 ELSE 0 END) AS null_brand_popularity,\n  SUM(CASE WHEN price IS NULL THEN 1 ELSE 0 END) AS null_price\nFROM \'Automotive Price Prediction-20260918-042121.csv\';',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_4

,null_make,null_model,null_year,null_mileage,null_engine_hp,null_transmission,null_fuel_type,null_drivetrain,null_body_type,null_exterior_color,null_interior_color,null_owner_count,null_accident,null_seller_type,null_condition,null_trim,null_vehicle_age,null_mileage_per_year,null_brand_popularity,null_price
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# CEK DUPLIKAT

In [3]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_5 = _dntk.execute_sql(
  'SELECT make, model, year, mileage, price, COUNT(*) as jml\nFROM \'Automotive Price Prediction-20260918-042121.csv\'\nGROUP BY make, model, year, mileage, price\nHAVING COUNT(*) > 1;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_5

              make       model  year  mileage   price  jml
0              Kia       Forte  2010   300000  1500.0   16
1             Ford      Escape  2010   233786  1500.0    2
2           Toyota       Camry  2013   300000  1500.0   20
3            Dodge     Charger  2009   300000  1500.0   36
4            Lexus          GX  2007   300000  1500.0   12
..             ...         ...   ...      ...     ...  ...
815          Dodge     Durango  2002   300000  1500.0    2
816         Nissan       Titan  2014   233113  1500.0    2
817  Mercedes-Benz     S-Class  2003   300000  1500.0    2
818         Toyota  Highlander  2014   300000  1500.0    3
819          Tesla     Model Y  2005   300000  1500.0    2

[820 rows x 6 columns]

# MENGATASI DATA DUPLIKAT

In [4]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_12 = _dntk.execute_sql(
  'SELECT DISTINCT make, model, year, mileage, price\nFROM \'Automotive Price Prediction-20260918-042121.csv\'',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_12

            make      model  year  mileage     price
0          Tesla    Model Y  2019   107795  34357.06
1       Cadillac        XT5  2016   186260  24204.13
2           Audi         Q5  2010   300000   4436.75
3        Porsche    Cayenne  2021    62306  54892.80
4        Hyundai   Santa Fe  2023    33538  15411.00
...          ...        ...   ...      ...       ...
989468     Mazda     Mazda6  2017   145217   7834.80
989469   Porsche      Macan  2022    57878  57913.58
989470      Ford    Mustang  2021    34615  23394.93
989471    Subaru  Crosstrek  2016   175006   7152.42
989472     Dodge    Charger  2016    83990  13850.79

[989473 rows x 5 columns]

# CEK DATA BERSIH DARI DUPLIKAT

In [5]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{"sortBy":[],"filters":[],"pageSize":10,"pageIndex":0,"columnOrder":["make","model","year","mileage","jml"],"hiddenColumnIds":[],"columnDisplayNames":[],"conditionalFilters":[],"cellFormattingRules":[],"wrappedTextColumnIds":[]}')
else:
  _deepnote_current_table_attrs = '{"sortBy":[],"filters":[],"pageSize":10,"pageIndex":0,"columnOrder":["make","model","year","mileage","jml"],"hiddenColumnIds":[],"columnDisplayNames":[],"conditionalFilters":[],"cellFormattingRules":[],"wrappedTextColumnIds":[]}'

df_14 = _dntk.execute_sql(
  'SELECT make, model, year, mileage, price,  COUNT(*) as jml\nFROM df_12\nGROUP BY make, model, year, mileage, price\nHAVING COUNT(*) > 1',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_14

Empty DataFrame
Columns: [make, model, year, mileage, price, jml]
Index: []

# CEK DATA ANEH

In [6]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_6 = _dntk.execute_sql(
  'SELECT * FROM \'Automotive Price Prediction-20260918-042121.csv\'\nWHERE \n  price <= 0 \n  OR year > 2026 OR year < 1900\n  OR mileage < 0 \n  OR engine_hp <= 0\n  OR vehicle_age < 0\nLIMIT 10;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_6

Empty DataFrame
Columns: [make, model, year, mileage, engine_hp, transmission, fuel_type, drivetrain, body_type, exterior_color, interior_color, owner_count, accident_history, seller_type, condition, trim, vehicle_age, mileage_per_year, brand_popularity, price]
Index: []

# CEK TYPO DI KOLOM TEKS

In [7]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_7 = _dntk.execute_sql(
  'SELECT DISTINCT transmission FROM \'Automotive Price Prediction-20260918-042121.csv\';\nSELECT DISTINCT fuel_type FROM \'Automotive Price Prediction-20260918-042121.csv\';\nSELECT DISTINCT drivetrain FROM \'Automotive Price Prediction-20260918-042121.csv\';\nSELECT DISTINCT condition FROM \'Automotive Price Prediction-20260918-042121.csv\';',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_7

   condition
0  Excellent
1       Fair
2       Good

# STATISTIK AWAL

In [8]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_9 = _dntk.execute_sql(
  'SELECT \n  MIN(price) as harga_terendah,\n  MAX(price) as harga_termahal,\n  AVG(price) as rata_harga,\n  AVG(mileage) as rata_km\nFROM \'Automotive Price Prediction-20260918-042121.csv\';',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_9

   harga_terendah  harga_termahal    rata_harga        rata_km
0          1500.0        93422.09  20329.302593  112660.126464

# CEK DATA HARGA YANG PALING RENDAH

In [9]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_10 = _dntk.execute_sql(
  'SELECT make, model, year, mileage, condition, price\nFROM \'Automotive Price Prediction-20260918-042121.csv\'\nORDER BY price ASC\nLIMIT 10;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_10

         make       model  year  mileage  condition   price
0        Ford    Explorer  2013   234866  Excellent  1500.0
1     Hyundai    Santa Fe  2014   254513       Good  1500.0
2       Dodge  Challenger  2008   240744       Good  1500.0
3  Volkswagen      Tiguan  2010   189574       Good  1500.0
4     Hyundai      Tucson  2013   172846  Excellent  1500.0
5     Hyundai      Tucson  2010   173846  Excellent  1500.0
6       Honda        CR-V  2012   212925       Good  1500.0
7      Subaru   Crosstrek  2012   256509  Excellent  1500.0
8  Volkswagen      Tiguan  2004   261123       Good  1500.0
9        Ford       Focus  2013   272389       Good  1500.0

# ANALISIS HARGA MOBIL

In [10]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_11 = _dntk.execute_sql(
  'SELECT \n  COUNT(*) as total,\n  SUM(CASE WHEN price < 5000 THEN 1 ELSE 0 END) as harga_di_bawah_5000,\n  SUM(CASE WHEN price > 80000 THEN 1 ELSE 0 END) as harga_di_atas_80000\nFROM \'Automotive Price Prediction-20260918-042121.csv\';',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_11

     total  harga_di_bawah_5000  harga_di_atas_80000
0  1000000             104532.0                590.0

### Terlihat dari 1\.000\.000 data pada tabel diatas, bahwa harga mobil di bawah 5000 ada sekitar 104\.532 unit dan harga di atas 80000 hanya ada 590 unit\. Jadi, pada perusahaan / pasar didominasi mobil yang haga nya murah\.

# ANALISIS TAHUN MOBIL BERDASARKAN HARGA

In [11]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_18 = _dntk.execute_sql(
  'SELECT year, (2026 - year) as umur,\nAVG (price) as harga_rata_rata\nFROM \'Automotive Price Prediction-20260918-042121.csv\'\nGROUP BY year\nORDER BY umur\nLIMIT 10;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_18

   year  umur  harga_rata_rata
0  2025     1     39425.809336
1  2024     2     39009.840298
2  2023     3     35301.978666
3  2022     4     31898.795453
4  2021     5     28731.708644
5  2020     6     25946.043566
6  2019     7     23122.997721
7  2018     8     20554.706080
8  2017     9     18080.292150
9  2016    10     15807.076166

### Terlihat pada tabel data diatas  jika rentang umur mobil yaitu umur 1\- 16 tahun, dengan mayoritas 5\-10 tahun\. Semakin tua umur mobil, harga nya semakin turun\.

# ANALISIS MEREK MOBIL TERMAHAL

In [12]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_13 = _dntk.execute_sql(
  'SELECT make, COUNT(*) as jumlah_mobil, ROUND(AVG(price)) as harga_rata_rata\nFROM df_12\nGROUP BY make\nORDER BY harga_rata_rata DESC',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_13

             make  jumlah_mobil  harga_rata_rata
0         Porsche         40210          43005.0
1      Land Rover         40133          39501.0
2           Tesla         40221          32423.0
3        Cadillac         39832          30396.0
4   Mercedes-Benz         39767          29142.0
5            Audi         39983          27637.0
6           Volvo         39780          27003.0
7             BMW         39737          25546.0
8           Lexus         39752          24189.0
9           Acura         39859          22072.0
10            GMC         39250          19433.0
11            Ram         39599          18790.0
12       Chrysler         39447          18081.0
13           Jeep         39421          16773.0
14          Dodge         39311          16031.0
15      Chevrolet         39323          15344.0
16           Ford         39116          14038.0
17         Subaru         39538          13334.0
18     Volkswagen         39335          12699.0
19         Toyota         38954          11964.0
20          Mazda         39528          11695.0
21          Honda         39362          11366.0
22         Nissan         39516          10689.0
23            Kia         39850          10381.0
24        Hyundai         38649          10018.0

### Dari analisis tabel diatas, dapat disimpulkan bahwa Porsche jari merek paling mahal dengan rata\-rata harga jual 43\.005, diikuti Land Rover 39\.501 dan Tesla 32\.423\. Jumlah mobil tiap merek hampir merata sekitar 39 sampai 40 ribu unit, jadi perbadingan setiap unit adil\.

# ANALISIS PENGARUH KILOMETER TERHADAP HARGA RATA \- RATA MOBIL

In [15]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_16 = _dntk.execute_sql(
  'SELECT \n  CASE \n    WHEN mileage < 50000 THEN \'Rendah <50k\'\n    WHEN mileage < 100000 THEN \'Sedang 50-100k\'\n    WHEN mileage < 200000 THEN \'Tinggi 100-200k\'\n    ELSE \'Ekstrim >200k\'\n  END as kelompok_km,\n  COUNT(*) as jumlah,\n  ROUND(AVG(price)) as harga_rata_rata\nFROM df_12\nGROUP BY kelompok_km\nORDER BY harga_rata_rata DESC',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_16

       kelompok_km  jumlah  harga_rata_rata
0      Rendah <50k  211496          32811.0
1   Sedang 50-100k  270488          23628.0
2  Tinggi 100-200k  390217          15646.0
3    Ekstrim >200k  117272           7485.0

### Dari analisis pada tabel diatas, harga turun drastis seiring kilometer naik\. Pada data dijelaskan bahwa mobil kategori rendah <50k harga rata\-rata 32\.811, sedangkan  mobil kategori ekstrim\>200k hanya 7\.485\. Jadi, dapat disimpulkan bahwa selisihnya bisa 4x lipat\. Bukti, makin jauh perjalanan makin murah harganya\.

# ANALISIS HARGA BERDASARKAN MEREK MOBIL DAN TAHUN

In [17]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{"sortBy":[],"filters":[],"pageSize":10,"pageIndex":0,"columnOrder":["make","year","harga_rata_rata"],"hiddenColumnIds":[],"columnDisplayNames":[],"conditionalFilters":[],"cellFormattingRules":[],"wrappedTextColumnIds":[]}')
else:
  _deepnote_current_table_attrs = '{"sortBy":[],"filters":[],"pageSize":10,"pageIndex":0,"columnOrder":["make","year","harga_rata_rata"],"hiddenColumnIds":[],"columnDisplayNames":[],"conditionalFilters":[],"cellFormattingRules":[],"wrappedTextColumnIds":[]}'

df_17 = _dntk.execute_sql(
  'SELECT make, year, ROUND(AVG(price)) as harga_rata_rata\nFROM df_12\nWHERE make IN (\'Toyota\',\'BMW\',\'Ford\',\'Honda\')\nGROUP BY make, year\nORDER BY make, year',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_17

       make  year  harga_rata_rata
0       BMW  2001           1506.0
1       BMW  2002           1500.0
2       BMW  2003           2091.0
3       BMW  2004           3527.0
4       BMW  2005           2254.0
..      ...   ...              ...
96   Toyota  2021          18076.0
97   Toyota  2022          20554.0
98   Toyota  2023          23045.0
99   Toyota  2024          25543.0
100  Toyota  2025          26138.0

[101 rows x 3 columns]

### Analisis pada tabel diatas, menunjukkan perbandingan harga rata\-rata 4 merek \(BMW, Ford, Honda, Toyota\) berdasarkan tahun produksi 2000\-2025\.

### 1\.  Tren Umum Naik: Keempat merek menunjukkan tren kenaikan harga yang signifikan seiring tahun yang lebih muda\. Contoh BMW tahun 2001 hanya 1\.506, namun di tahun 2025 mencapai 47\.363 atau naik 31x lipat\.

### 2\.  BMW Paling Mahal & Konsisten: BMW konsisten menjadi merek termahal di setiap tahunnya\. Di tahun 2020 BMW sudah 32\.004, sedangkan Ford 18\.378, Honda 15\.142, Toyota \(2014\) 5\.117\. Ini membuktikan merek premium memiliki nilai jual kembali yang lebih tinggi\.

### 3\.  Anomali Harga 1\.500 & Fluktuasi: Pada tahun 2000\-2004 semua merek Ford, Honda, Toyota flat di harga 1\.500, ini memberi tanda batas minimal harga \(floor price\) pada dataset\. Fluktuasi naik turun seperti Ford 2007 2\.371 turun ke 2008 2\.156 dan Honda 2005 1\.798 turun ke 2006 1\.507 disebabkan perbedaan tipe varian dan mil di tahun tersebut, bukan penurunan pasar\.

### Kesimpulannya, tahun produksi adalah faktor utama penentu harga, dengan merek menjadi faktor pembeda kedua\.

### Note: Untuk data harga 1500, ditetapkan minimal harga / harga terendah bertujuan untuk menghindari nilai 0 atau outlier yang mengganggu perhitungan rata\-rata\.

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=e94e5198-3a5e-4d12-b960-a95c93b4d83b' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' />
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>